# Usa una imagen base de Node.js para construir la aplicación
FROM node:16 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Construye la aplicación
RUN npm run build

# Usa una imagen de servidor web para servir la aplicación
FROM nginx:alpine

# Copia los archivos construidos desde el paso anterior
COPY --from=build /app/build /usr/share/nginx/html

# Exponer el puerto que el contenedor usará
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
